### ISSUE TITLE
msbuild error MSB4025

### ISSUE THREAD

**Issue by stihie** [nodejs/node-gyp#1144]
I'm using `Windows 10`, node `7.7.2`, npm `4.1.2`

I get this error when running `node-gyp rebuild` for after installing the binding module `leveldown` (My objective is to rebuild it for electron). The specific error is...

```
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
```
I searched for this error but it seemed to be specific to visual studio projects and xml files. I don't have a lot of context since I'm not usually a windows user. Somewhere I found that you can specific `--msvs_version=2013`, that did not work. But I tried with `2017` (because that's the latest download) and I got the following error.

```
Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\Gebruiker\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
```

If anyone has any idas I would be very grateful!
-S

**Comment by bnoordhuis** [comment]
VS 2017 isn't supported yet (see WIP in #1130) but if you install 2015 and pass `--msvs_version=2015`, it should work.

**Comment by simonbuchan** [comment]
Except it uses the `msbuild.exe` on the path by default, so you need to either ensure the v14.0 msbuild in `%PROGRAM_FILES(x86)%\MSBuild\v14.0\Bin` is the one it finds, or install the v140 C++ toolchain in VS 2017. Ugh.

**Comment by refack** [comment]
> Except it uses the msbuild.exe on the path by default, so you need to either ensure the v14.0 msbuild in %PROGRAM_FILES(x86)%\MSBuild\v14.0\Bin is the one it finds, or install the v140 C++ toolchain in VS 2017. Ugh.

3.6.0 supports VS2017
You can install [`Build Tools for Visual Studio 2017`](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15), make sure to select `C++ tools`, `Windows 10 SDK` and `MSBuild` and your set.

This bug can be closed /cc @rvagg

**Comment by madcampos** [comment]
I'm still getting this error with `Windows 10`, node `7.8.0`, npm `4.2.0` and node-gyp `3.6.0`

**Comment by himadrinath** [comment]
@refack after installing [VS 2017 C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) as u mention side by side with VS2017 community edition. 

`C:\Users\himad\Desktop\testProject\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1918, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'`

**Comment by refack** [comment]
@himadrinath checking...
P.S. You don't have to install the Buildtools side by side, just make sure you have the three features installed in the "community edition" Instance

**Comment by refack** [comment]
@himadrinath try and set `GYP_MSVS_VERSION=2015` before you `npm i`
(At the time of the release of 3.6.0 `GYP` did not know what 2017 was)

**Comment by himadrinath** [comment]
@refack  after set GYP_MSVS_VERSION=2015 getting this one

`C:\Users\himad\Desktop\testProject\node_modules\sharp\build\libvips-cpp.vcxproj(20,3): error MSB4019: The imported proj
ect "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and t
hat the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\himad\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\himad\Desktop\testProject\node_modules\sharp
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm WARN testproject@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\himad\AppData\Roaming\npm-cache\_logs\2017-04-17T22_17_30_270Z-debug.log`

![1](https://cloud.githubusercontent.com/assets/12247490/25107009/6e746d40-23ea-11e7-99c0-1a5a031ad4e5.png)
![2](https://cloud.githubusercontent.com/assets/12247490/25107017/76cc73a2-23ea-11e7-9c58-d6972a1168f7.png)

**Comment by refack** [comment]
Everything seems file...
Could you run
```cmd
cd /d C:\Users\himad\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\
powershell.exe -ExecutionPolicy Unrestricted -Command "&{Add-Type -Path 'Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query(); }"
```
You should see some JSON output similar to:
```json
{"log":"Found installation at: D:\\bin\\dev\\VS\\2017\\BuildTools\n  - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64\n  - Found Microsoft.VisualStudio.Component.Windows10SDK.14393\n  - Found Microsoft.VisualStudio.VC.MSBuild.Base\n  - Using this installation with Windows 10 SDK","path":"D:\\bin\\dev\\VS\\2017\\BuildTools","sdk":"10.0.14393.0"}
```
Could you post it?

**Comment by himadrinath** [comment]
@refack 

`Exception calling "Query" with "0" argument(s): "Input string was not in a correct format."
At line:1 char:36
+ ...  -Path 'Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query(); }
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException`

**Comment by refack** [comment]
Seems like you have a non "canonical" node-gyp. Do:
```cmd
cd /d C:\Users\himad\AppData\Roaming\npm\node_modules\npm
npm rm node-gyp
npm i node-gyp@3.6.0 --no-link
```

**Comment by himadrinath** [comment]
@refack 

`C:\Users\himad\AppData\Roaming\npm\node_modules\npm>npm rm node-gyp
- balanced-match@0.4.2 node_modules\balanced-match
- concat-map@0.0.1 node_modules\concat-map
- brace-expansion@1.1.7 node_modules\brace-expansion
- minimatch@3.0.3 node_modules\minimatch
- nopt@3.0.6 node_modules\node-gyp\node_modules\nopt
- node-gyp@3.6.0 node_modules\node-gyp

C:\Users\himad\AppData\Roaming\npm\node_modules\npm>npm i node-gyp@3.6.0 --no-link
npm@4.5.0 C:\Users\himad\AppData\Roaming\npm\node_modules\npm
`-- node-gyp@3.6.0
  +-- minimatch@3.0.3
  | `-- brace-expansion@1.1.7
  |   +-- balanced-match@0.4.2
  |   `-- concat-map@0.0.1
  `-- nopt@3.0.6`

**Comment by refack** [comment]
That's it. Now try and `npm i` your `testProject`

**Comment by himadrinath** [comment]
@refack after following the process as you told. one of my other machine i just installed VS 2017 C++ Build Tools and test it. its work fine

![response](https://cloud.githubusercontent.com/assets/12247490/25119156/a6df09b4-2436-11e7-93db-094e7c3c54b8.png)

but still getting the same result into another machine where i just installed VS2017 Community

`Exception calling "Query" with "0" argument(s): "Input string was not in a correct format."
At line:1 char:36
+ ...  -Path 'Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query(); }
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException`

**Comment by refack** [comment]
This is quite strange since in the code that was distributed with `node-gyp@3.6.0`  `Query` take 0 arguments.
So my intuition was  that you have a non-release version of `node-gyp` somewhere. But further investigation says different. I think that there's an error _in_ the `.cs` file. We haven't seen that before...

There are a few thing we could try to solve this, and a few to try and figure out what's wrong:
To solve:
1. try to run from an "as Administrator" cmd.exe. Maybe it'll help
2. try to run from a "VS dev console" (you get shortcuts installed in the start menu by the Visual Studio Installer)

To figure out:
1. do a sanity check for COM
```cmd
powershell.exe -ExecutionPolicy Unrestricted -Command "if (Test-Path 'Registry::HKEY_CLASSES_ROOT\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}') { echo 'found' } else {echo 'not found'}"
```
  This should yield `found`

2. download `vswhere` by Microsoft https://github.com/Microsoft/vswhere, follow the readme, and see if it can find the VS installation

3. We could coordinate a remove access session (TeamViewer / RDP / VNC), and I'll try to find what fails.

**Comment by himadrinath** [comment]
@refack 

![found](https://cloud.githubusercontent.com/assets/12247490/25133766/4c9dd464-246b-11e7-866c-cb8b13d7f9c8.gif)

**Comment by refack** [comment]
Thanks.🤔🤔🤔

**Comment by himadrinath** [comment]
@refack but the problem is on............................

**Comment by refack** [comment]
🤔🤔🤔🤔 Still thinking...
(did you check is `vswhere` works?)

**Comment by himadrinath** [comment]
@refack  working on that...........

**Comment by refack** [comment]
Another helpful test would be for you to clone https://github.com/node4good/windows-autoconf
and run
```cmd
Tools\try_powershell.cmd
```
and paste the resulting JSON
or
```cmd
Tools\try_powershell.cmd > out.josn
```
and upload `out.json` (just drag&drop it here)

**Comment by himadrinath** [comment]
@refack 

`Add-Type : c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(31) : The type or namespace name 'VSInstance' could not be 
found (are you missing a using directive or an assembly reference?)
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(30) : 
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(31) : >>>         public static string ToJSON(VSInstance inst)
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(32) :         {
At line:1 char:5
+ & { Add-Type (Out-String -InputObject (Get-Content '..\tools*\*.cs')) ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except 
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(65) : The type or namespace name 'VSInstance' could not be 
found (are you missing a using directive or an assembly reference?)
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(64) : 
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(65) : >>>         public static string ToJSON(IEnumerable<VSInstance> 
insts)
c:\Users\himad\AppData\Local\Temp\px25s2n1.0.cs(66) :         {
At line:1 char:5
+ & { Add-Type (Out-String -InputObject (Get-Content '..\tools*\*.cs')) ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except 
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
Add-Type : Cannot add type. Compilation errors occurred.
At line:1 char:5
+ & { Add-Type (Out-String -InputObject (Get-Content '..\tools*\*.cs')) ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
 
Unable to find type [VisualStudioConfiguration.Program].
At line:1 char:72
+ ... ntent '..\tools*\*.cs')); [VisualStudioConfiguration.Program]::Query( ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VisualStudioConfiguration.Program:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
`

**Comment by refack** [comment]
My bad, I'm using git sub-modules, you need to pull them as well
```
git submodule update --init --recursive
```

**Comment by himadrinath** [comment]
@refack how can i gave u team viewer credentials securely. so u can test your self

**Comment by refack** [comment]
refack@gmail.com

**Comment by himadrinath** [comment]
@refack send

**Comment by himadrinath** [comment]
@refack i don't know how to thank you. it's been more then 5 to 7 days i was trying to solve it. this is my first time in node and first package i installed. thank you is not enough...........

**Comment by refack** [comment]
@joaocgreis we have a bug in [Find-VS2017.cs#L232](https://github.com/nodejs/node-gyp/blob/master/lib/Find-VS2017.cs#L232)
New SDK moniker is `10.0.15063.Desktop` ParseInt borkes out :) I'm making a PR.

**Comment by refack** [comment]
> @refack i don't know how to thank you. it's been more then 5 to 7 days i was trying to solve it. this is my first time in node and first package i installed. thank you is not enough...........

@himadrinath Ohh man, what a hard first time. I've seen like 100,000 package installs first time it's so hard. If you are a bug magnet I want to hire you as QA 😜

**Comment by refack** [comment]
@himadrinath could you open a new issue here in `node-gyp`: "v3.6.0 incompatible with super new SDKs 10.0.15063.Desktop"
And ref this one

**Comment by bnoordhuis** [comment]
I think this has been answered; it certainly digressed.  Closing.

**Comment by skynode** [comment]
@refack Sorry, just checking, has this bug been fixed in node-gyp@3.6.1? I'm seeing the same problems with node-gyp as @himadrinath. I'm running 3.6.1. How do I proceed?

**Comment by refack** [comment]
Not fixed yet, you need to uninstall the new SDK version...

for `node-gyp@3.6.0` do not install any of the special SDKs (red) only any of the greens
![image](https://cloud.githubusercontent.com/assets/96947/25140916/dbbabd42-242f-11e7-9f7d-aa724618ddd3.png)
P.S. you only need one, and best tested is 14393

**Comment by skynode** [comment]
Thank you. I'm currently uninstalling Win10SDK_10.0.15063.Desktop. 

I need to know, with multiple versions, in my case:

![sdkcapture](https://cloud.githubusercontent.com/assets/17997010/26024554/8f5c6d7e-37cb-11e7-9b47-d7c9afbd81df.PNG)

Which one gets selected? 

P.S. I need 10586.0 in order to run native Python workloads.

**Comment by skynode** [comment]
Still getting the errors. Please what should be the contents of `.npmrc`?

**Comment by refack** [comment]
@skynode I'll need some information from your computer, so it's best that you open a new issue and post it there.
1. a good "sanity check" for VS2017 is to run `powershell.exe -ExecutionPolicy Unrestricted -Command "if (Test-Path 'Registry::HKEY_CLASSES_ROOT\CLSID\{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D}') { echo 'found' } else {echo 'not found'}"` and make sure it outputs `found`
2. Put the whole error output you get (like https://github.com/nodejs/node-gyp/issues/1144#issuecomment-294585334). You can attach it as text file or a [GitHub Gist](https://gist.github.com/).
3. clone or `npm i` [`windows-autoconf`](https://github.com/node4good/windows-autoconf) (if you clone use `--recurse-submodules` since I have submodules there)  
   Then from inside the `windows-autoconf` directory run `Tools\try_powershell.cmd > skynode.json` and attach the saved json file
4. Take a wider screenshot of the selection in your VSInstaller
5. run `npm config list` and paste the output.

**Comment by skynode** [comment]
Okay. Here goes:

1. Outputs `found`

2. See error output in this [gist](https://gist.github.com/skynode/23ca83c498fa84f8f30c2b410b941bfa)

3. Done this. [See this gist](https://gist.github.com/skynode/9103f2cb4948e0ddaac87779e03f9ef2)

4. 
![vsix-image](https://cloud.githubusercontent.com/assets/17997010/26027446/018f5d2c-3806-11e7-9d5d-e8e112019941.PNG)

5. See [gist](https://gist.github.com/skynode/50dfce0ddf6281288b61ed578ede4f3f)

**Comment by refack** [comment]
@skynode if you are handy with git, fetch the fix #1198 unto your `node-gyp` installation (`C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp`)

The more direct way is to right click [this link](https://github.com/refack/node-gyp/raw/d067e3ad7d54f4ed33beed99976393eebd322ad9/lib/Find-VS2017.cs) and save as...
`C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\\node gyp\lib\Find-VS2017.cs`

**Comment by skynode** [comment]
@refack After replacing fetching and replacing `Find-VS2017.cs` , see new error [here](https://gist.github.com/skynode/4930774bae9e05f86db73bded9978f5c). 
Guess I may have to reinstall `SDK-15063` ? 

Using `WSL` successfully in the meantime.

**Comment by refack** [comment]
> Guess I may have to reinstall SDK-15063 ?

I suppose so, it didn't get uninstalled completely enough, VSInstaller still reported it as available.

If it's your own addon you're trying to build, you can add
```python
  "target_defaults": {
    "msvs_windows_target_platform_version": "10.0.14393.0"
  },
```
To the head of the `binding.gyp` file

**Comment by Loghorn** [comment]
I had the same issue and I found to be related to having installed `USB Device Connectivity`
![image](https://user-images.githubusercontent.com/2026182/43396965-9b4a1fce-9403-11e8-9d3f-8003bd22d333.png)
Uninstalling that component fixed the issue. I'm going to submit a small PR to fix the issue even if you install that component.

**Comment by MadOPcode** [comment]
'KeyError: '2017'' is present in @3.8.0

C:\Development\TypeScript\projects\<project>>npm i -S better-sqlite3

> integer@1.0.5 install C:\Development\TypeScript\projects\<project>\node_modules\integer
> node-gyp rebuild


C:\Development\TypeScript\projects\<project>\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)

KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<User>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Development\TypeScript\projects\<project>\node_modules\integer
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN <project>@0.0.1 No description
npm WARN <project>@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<User>\AppData\Roaming\npm-cache\_logs\2018-08-24T20_38_31_982Z-debug.log

**Comment by jzatarain** [comment]
With windows sdk v10.0.14393.795, it works correctly. This should be at the home page, IMO.

**Comment by pavanIT1996** [comment]
..\fs-ext.cc(108): warning C4996: 'Nan::NanErrnoException': was declared deprecated [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxp
roj]
  C:\Users\Pavan\Desktop\TodayServer\node_modules\nan\nan.h(862): note: see declaration of 'Nan::NanErrnoException'
..\fs-ext.cc(195): error C3861: 'fcntl': identifier not found [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(297): warning C4996: 'Nan::NanErrnoException': was declared deprecated [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxp
roj]
  C:\Users\Pavan\Desktop\TodayServer\node_modules\nan\nan.h(862): note: see declaration of 'Nan::NanErrnoException'
..\fs-ext.cc(339): warning C4996: 'Nan::NanErrnoException': was declared deprecated [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxp
roj]
  C:\Users\Pavan\Desktop\TodayServer\node_modules\nan\nan.h(862): note: see declaration of 'Nan::NanErrnoException'
..\fs-ext.cc(374): error C3861: 'fcntl': identifier not found [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(375): warning C4996: 'Nan::NanErrnoException': was declared deprecated [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxp
roj]
  C:\Users\Pavan\Desktop\TodayServer\node_modules\nan\nan.h(862): note: see declaration of 'Nan::NanErrnoException'
..\fs-ext.cc(433): warning C4996: 'Nan::NanErrnoException': was declared deprecated [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxp
roj]
  C:\Users\Pavan\Desktop\TodayServer\node_modules\nan\nan.h(862): note: see declaration of 'Nan::NanErrnoException'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN todayserver@1.0.0 No description
npm WARN todayserver@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules\fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1


How i fixed this error guys!!!

**Comment by richardlau** [comment]
> ..\fs-ext.cc(195): error C3861: 'fcntl': identifier not found [C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext\build\fs-ext.vcxproj]

@pavanIT1996 You need a later version of `fs-ext` that includes https://github.com/baudehlo/node-fs-ext/pull/70: https://github.com/baudehlo/node-fs-ext/issues/57

**Comment by richardlau** [comment]
The version of `fs-ext` in `C:\Users\Pavan\Desktop\TodayServer\node_modules\qlobber-fsq\node_modules\fs-ext` is `fs-ext@0.5.0`:

> ```
> fs-ext@0.5.0 install C:\Users\Pavan\Desktop\TodayServer\node_modules\qlobber-fsq\node_modules\fs-ext
> ```

It looks like `fs-ext@1.2.1` in `C:\Users\Pavan\Desktop\TodayServer\node_modules\fs-ext` built with no errors. In any case this doesn't look like an issue with `node-gyp`.

**Comment by pavanIT1996** [comment]
@richardlau  My package have versions have like this
```

{
  "name": "todayserver",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.4",
    "fs-ext": "^1.2.1",
    "mosca": "^2.8.3",
    "mqtt": "^2.18.8",
    "node-gyp": "^3.8.0",
    "path": "^0.12.7",
    "windows-build-tools": "^5.0.0"
  }
}

```

**Comment by richardlau** [comment]
> 
> 
> @richardlau My package have versions have like this
> 
> ```
> 
> {
>   "name": "todayserver",
>   "version": "1.0.0",
>   "description": "",
>   "main": "server.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "start": "node server.js"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "express": "^4.16.4",
>     "fs-ext": "^1.2.1",
>     "mosca": "^2.8.3",
>     "mqtt": "^2.18.8",
>     "node-gyp": "^3.8.0",
>     "path": "^0.12.7",
>     "windows-build-tools": "^5.0.0"
>   }
> }
> ```

One of those dependencies is dependent on (or dependent on something else that is dependent on) an older version of `qlobber-fsq`, which in turn is dependent on an older `fs-ext`.

> ```
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 (node_modules\qlobber-fsq\node_modules\fs-ext):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.5.0 install: `node-gyp configure build`
> ```

These lines indicate that `fs-ext` is an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies) anyway, so the failure to install `fs-ext@0.5.0` may not be a problem.

**Comment by ElectronicLove** [comment]
So who really solved this problem and how? I've tried everything still this error.

**Comment by abdelrady** [comment]
@hengkx Check this comment 
https://github.com/nodejs/node-gyp/issues/1144#issuecomment-290253041

**Comment by hengkx** [comment]
> @hengkx Check this comment
> [#1144 (comment)](https://github.com/nodejs/node-gyp/issues/1144#issuecomment-290253041)

Tried no effect

**Comment by vahydr** [comment]
I literally tested everything above , everything ! doesn't work and I had to uninstall node js and it's components completely, installed it again and now everything is working nice and smooth ! believe me I tried everything, that was the best solution for me

**Comment by endnch** [comment]
I solved this error by running `npm install --global --production windows-build-tools --vs2015` (note the `--vs2015`)

**Comment by LukiRe** [comment]
As @MadOPcode already pointed out, `KeyError: '2017'` is present in 3.8.0.

Windows 10, VS2017, Python2.7 installed.

Claims to not be able to find VS2017 through powershell.

<details>
<summary>Run of node-gyp configure --verbose in some directory:
</summary>
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\lksri\AppData\Roaming\npm\node_modules\node-gyp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\lksri\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.14
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.0
gyp verb command install [ '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.15.0
gyp verb build dir attempting to create "build" dir: C:\WINDOWS\system32\build
gyp verb build dir "build" dir needed to be created? C:\WINDOWS\system32\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017

And goes on to complain that this directory actually isnt a node project.
</details>

**Comment by Chrissie** [comment]
@Noxillio 

#1691 Is the same problem. For me the solution was to `npm config delete msvs_version` and `npm config delete msvs_version -g`

**Comment by notalk0** [comment]
For my case, i just want to install bcrypt in angular 8 app, 
here is how is the story i finally get it work:

First, this is what the error I get:
![111](https://user-images.githubusercontent.com/9769260/59586891-877dfe00-9116-11e9-829f-c6a4dfa67a68.JPG)

It say can't find python, then I try run this in administrator terminal:
```
npm install --global --production windows-build-tools
npm install node-gyp
```

Then i try install bcrypt, i get some header files missing:
![22222](https://user-images.githubusercontent.com/9769260/59587049-f0657600-9116-11e9-9aaa-0e0aeab56934.JPG)

After google, i get my Windows 10 SDK via Visual Studio Installer
![333](https://user-images.githubusercontent.com/9769260/59587293-87cac900-9117-11e9-8c9e-ec8995098e09.JPG)

Then i try again install bcrypt, get another error "**MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing**", which lead me here:
![4444](https://user-images.githubusercontent.com/9769260/59587472-e8f29c80-9117-11e9-8581-234686762073.JPG)


Finally, i run this command from https://github.com/nodejs/node-gyp/issues/1144#issuecomment-450620159, it get me works:
```
npm install --global --production windows-build-tools --vs2015
npm install node-gyp
npm install node-gyp -g
```

LOL
![66666](https://user-images.githubusercontent.com/9769260/59587647-569ec880-9118-11e9-9ba1-ab199764e36d.JPG)

**Comment by SabariCG** [comment]
error MSB8036: The Windows SDK version 8.1
as not found. Install the required version of Windows SDK or change the SDK ve
sion in the project property pages or by right-clicking the solution and selec
ing "Retarget solution".

**Comment by SabariCG** [comment]
node_modules\nan\nan.h(911)
: error C2661: 'v8::Value::ToString': no overloaded function takes 0 arguments
(compiling source file ..\src\leveldown_async.cc

**Comment by HarshKumar01** [comment]
> #1691 Is the same problem. For me the solution was to `npm config delete msvs_version` and `npm config delete msvs_version -g`

@Chrissie Thanks a lot. This worked for me. (I had VS2017 build tools installed)

**Comment by frlzjosh** [comment]
> For my case, i just want to install bcrypt in angular 8 app,
> here is how is the story i finally get it work:
> 
> First, this is what the error I get:
> ![111](https://user-images.githubusercontent.com/9769260/59586891-877dfe00-9116-11e9-829f-c6a4dfa67a68.JPG)
> 
> It say can't find python, then I try run this in administrator terminal:
> 
> ```
> npm install --global --production windows-build-tools
> npm install node-gyp
> ```
> 
> Then i try install bcrypt, i get some header files missing:
> ![22222](https://user-images.githubusercontent.com/9769260/59587049-f0657600-9116-11e9-9aaa-0e0aeab56934.JPG)
> 
> After google, i get my Windows 10 SDK via Visual Studio Installer
> ![333](https://user-images.githubusercontent.com/9769260/59587293-87cac900-9117-11e9-8c9e-ec8995098e09.JPG)
> 
> Then i try again install bcrypt, get another error "**MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing**", which lead me here:
> ![4444](https://user-images.githubusercontent.com/9769260/59587472-e8f29c80-9117-11e9-8581-234686762073.JPG)
> 
> Finally, i run this command from [#1144 (comment)](https://github.com/nodejs/node-gyp/issues/1144#issuecomment-450620159), it get me works:
> 
> ```
> npm install --global --production windows-build-tools --vs2015
> npm install node-gyp
> npm install node-gyp -g
> ```
> 
> Result:
> ![66666](https://user-images.githubusercontent.com/9769260/59587647-569ec880-9118-11e9-9ba1-ab199764e36d.JPG)

works like a charm! I was stubborn to keep on using `npm install --global --production windows-build-tools --vs2017` and `--vs2019` as I am using those Visual Studio versions, finally when I used the version suggested by the author everything else worked!

**Comment by cclauss** [comment]
https://www.npmjs.com/package/bcrypt is v4.0.1

**Comment by alfredbaudisch** [comment]
For whoever is still struggling Windows build errors due to the Build Tools, simplified instructions: https://github.com/nodejs/node-gyp/issues/2467#issuecomment-902003727
