### ISSUE TITLE
How to enable RTTI on Windows?

### ISSUE THREAD

**Issue by strrchr** [nodejs/node-gyp#857]
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(883): warning C 4541: 'dynamic_cast' used on polymorphic type 'rocksdb::TableFactory' with /GR-; unpr edictable behavior may result (compiling source file ..\deps\rocksdb\tools\sst_dump_t ool.cc) [D:\home\js\modules_by_me\rocksdown\build\rocksdb.vcxproj]
```
I tried these, but it seems not work.
```

    'conditions': [
        ['OS=="win"', {
            'msvs_settings': {
                'VCCLCompilerTool': {
                    'RuntimeTypeInfo': 'true',
                    'EnableFunctionLevelLinking': 'true',
                    'ExceptionHandling': '2',
                    'DisableSpecificWarnings': [ '4355', '4530' ,'4267', '4244' ],
                }
            },
            'cflags!': [ '/GR-' ],
            'cflags+': [ '/GR+' ],
```

**Comment by bnoordhuis** [comment]
`'RuntimeTypeInfo': 'true'` is the right switch.  Not sure why it isn't working for you.

**Comment by graysonlang** [comment]
I've seen this issue and the fix appears to be set the value in both Debug and Release configurations. Otherwise it doesn't properly override the default setting.

```
'conditions': [
  ['OS=="win"', {
    'configurations': {
      'Debug': {
        'msvs_settings': {
          'VCCLCompilerTool': {
            'RuntimeTypeInfo':
          },
        }
      }, # Debug
      'Release': {
          'VCCLCompilerTool': {
            'RuntimeTypeInfo': 'true',
          },
        },
      }, # Release
    }, # configurations
  } ], # OS=="win"
], # conditions
```

**Comment by bnoordhuis** [comment]
Looks like this is resolved.  I'll close.

**Comment by jvallesf** [comment]
> I've seen this issue and the fix appears to be set the value in both Debug and Release configurations. Otherwise it doesn't properly override the default setting.
> 
> ```
> 'conditions': [
>   ['OS=="win"', {
>     'configurations': {
>       'Debug': {
>         'msvs_settings': {
>           'VCCLCompilerTool': {
>             'RuntimeTypeInfo': 'true',
>           },
>         }
>       }, # Debug
>       'Release': {
>           'VCCLCompilerTool': {
>             'RuntimeTypeInfo': 'true',
>           },
>         },
>       }, # Release
>     }, # configurations
>   } ], # OS=="win"
> ], # conditions
> ```

This has been the solution in my case. Thanks!

**Comment by mmppeegg** [comment]
> I've seen this issue and the fix appears to be set the value in both Debug and Release configurations. Otherwise it doesn't properly override the default setting.
> 
I still fail on Release build...
Excuse me, may I know your version?
Mine:
Electron: 5.0.13
gode-gyp: 7.1.1
Visual Studio: VS2017 community
node: 10.16.0
bindings: 1.5.0

**Comment by jvallesf** [comment]
In my case, I don't use node-gyp anymore, I compile the bindings directly with Visual Studio. But at the time I was using the following:

Electron: 5.0.6
node-gyp: 5.0.3
Visual Studio: VS2015 community
node: 12.6.0
