### ISSUE TITLE
 error C2373: '__pfnDliNot ifyHook2': redefinition; different type modifiers

### ISSUE THREAD

**Issue by sduqlsc** [nodejs/node-gyp#980]
working on the first step of react native:
> C:\Users\xx\AndroidStudioProjects\AwesomeProject\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   validation.cc
>   win_delay_load_hook.c
> C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
> ifyHook2': redefinition; different type modifiers [C:\Users\xx\AndroidStudioProjects\AwesomeProject\node_modules
> \utf-8-validate\build\validation.vcxproj]
>   D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
>   ifyHook2'
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\xx\AndroidStudioProjects\AwesomeProject\node_modules\utf-8-validate
> gyp ERR! node -v v6.2.2
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
> npm WARN install:utf-8-validate@1.2.1 Exit status 1
> AwesomeProject@0.0.1 C:\Users\Mui Young\AndroidStudioProjects\AwesomeProject
> `-- react@15.2.0

**keep getting above error，with dev environment:**

1. VS 2015
2. win10 enterprise x64
3. python 2.7

**Comment by bnoordhuis** [comment]
Fixed in node-gyp@3.4.0 so please upgrade.  See also the several other issues that have been filed about that.

**Comment by sduqlsc** [comment]
hv updated using cmd 'npm install -g node-gyp' and 'node-gyp -v' shows the version is 3.4. However, using 'react-native init AwesomeProject' would still show the above error with the error info 'node-gyp -v v3.3.1'.

any idea, thanks?

**Comment by rvagg** [comment]
it's probably because you're using the version of node-gyp that comes with npm, either go to the npm installation directory and manually upgrade node-gyp there (tricky if you don't know where it is), or install a new version of npm.

If you're on an npm v2 then you should get v2.15.9, `npm i npm@2 -g` and it'll have a fix for you, if you're on npm v3 then you'll need v3.10.5 which is not the "latest" version, it's actually "next" (i.e. testing), so you'll need to `npm i npm@next -g` to get this on your system.

**Comment by sduqlsc** [comment]
thanks for the reply. i hv download latest version of gpy to replace and it's ok. 

btw, i think it should be mentioned in the readme document in case of 'detour', especially for beginners.
